### ISSUE TITLE
Распределение по нодам в зависимости от периодичности нагрузки для волатильных подов

### ISSUE THREAD

**Issue by nailgun** [smpio/kube-resource-analyzer#16]
Разделить сутки и неделю на "тайм-бакеты". Анализировать работу подов и выставлять для них podAntiAffinity preferredDuringScheduling.

Например, имеем под, который потребляет много памяти и CPU каждую ночь с 3 до 4. Для него добавится:

```
metadata:
  labels:
    kra-load-buckets.smp.io/mem-3h: yes
    kra-load-buckets.smp.io/cpu-3h: yes
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    podAffinityTerm:
      topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: kra-load-buckets.smp.io/mem-3h
          operator: Exists
  - weight: 1
    podAffinityTerm:
      topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: kra-load-buckets.smp.io/cpu-3h
          operator: Exists
```

Или под, котрый стартует каждую ночь с 2 и работает до 5, причём потребляет в основном только память:

```
metadata:
  labels:
    kra-load-buckets.smp.io/mem-2h: yes
    kra-load-buckets.smp.io/mem-3h: yes
    kra-load-buckets.smp.io/mem-4h: yes
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
  - weight: 1
    podAffinityTerm:
      topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: kra-load-buckets.smp.io/mem-2h
          operator: Exists
  - weight: 1
    podAffinityTerm:
      topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: kra-load-buckets.smp.io/mem-3h
          operator: Exists
  - weight: 1
    podAffinityTerm:
      topologyKey: kubernetes.io/hostname
      labelSelector:
        matchExpressions:
        - key: kra-load-buckets.smp.io/mem-4h
          operator: Exists
```

Таким образом эти два пода по возможности будут размещены на разных нодах, т.к. у них есть пересекающийся label `kra-load-buckets.smp.io/mem-3h`.
